### PR TITLE
Prototype player page redesign

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
On top of #4.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
Screenshot_2020-05-20 MrDizzy

**Comment by alexjurkiewicz** [comment]
[mobile view 1](https://user-images.githubusercontent.com/379509/82417420-df5b7c80-9abe-11ea-9ec3-433c6d47f9b1.png)
[mobile view 2](https://user-images.githubusercontent.com/379509/82417415-de2a4f80-9abe-11ea-94c4-0394fb26d6b1.png)

**Comment by alexjurkiewicz** [comment]
Current status:
Screenshot_2020-05-21 MrDizzy(1)
Screenshot_2020-05-21 MrDizzy(2)
Screenshot_2020-05-21 MrDizzy

**Comment by alexjurkiewicz** [comment]
Current status:

<details>
 <summary>Individual Categories</summary>
Screenshot_2020-05-21 MrDizzy
</details>

<details>
 <summary>Clan Categories</summary>
Screenshot_2020-05-21 MrDizzy(1)
</details>

<details>
 <summary>Banners</summary>
Screenshot_2020-05-21 MrDizzy(2)
</details>

**Comment by rawlins** [comment]
Any chance you could merge your docker commits that got rolled into this? I was actually going to use that too.

**Comment by ebering** [comment]
I think clan categories should only be displayed on the clan page, at least for mvp. If we have time we can go back and add in individual contributions to clan categories, but it's a bonus, not a requirement.

**Comment by alexjurkiewicz** [comment]
> I think clan categories should only be displayed on the clan page, at least for mvp. If we have time we can go back and add in individual contributions to clan categories, but it's a bonus, not a requirement.

The clan section will be showing the whole clan's results. So it might be a duplication of each clan's individual page too, but I think that's alright. If you prefer I can completely remove it though.

**Comment by alexjurkiewicz** [comment]
To Dos (convert to project board issues when this merges):

- [ ] Finalise colour scheme and apply to base
- [ ] Apply colour scheme to all pages
- [ ] Player page: Show Clan name
- [ ] Player page: Get images for these individual categories: nemex choice, high score, turn count win, realtime win, exploration, and god champion
- [ ] Player page: Get images for all clan categories
- [ ] Player page: make banners smaller (purely horizontal, smaller?)

**Comment by alexjurkiewicz** [comment]
merged manually

**Pull request closed without merging**
