### PR TITLE
Initial restyling

### PR DESCRIPTION
**Pull request by Kramin42**
Here's a quick pass at styling the website. Mostly I have only edited style.css except for removing styles coded in the html and some text-dark classes. **This hasn't been fully tested by running the python server, only the css has been tested with firefox dev tools.** If someone with the tournament scripts already set up could pull and test that would be great.

All the colors I chose are basic 3 digit hex values (e.g. #322 background) which were chosen very quickly and roughly, feel free to edit them.

Screen Shot 2020-06-12 at 3 47 58 PM
Screen Shot 2020-06-12 at 3 40 02 PM
Screen Shot 2020-06-12 at 3 08 44 PM
Screen Shot 2020-06-12 at 1 31 26 PM
Screen Shot 2020-06-12 at 1 31 08 PM
Screen Shot 2020-06-12 at 1 30 48 PM
Screen Shot 2020-06-12 at 3 53 16 PM

### CODE REVIEW

**Comment by aidanholm** [comment]
The purple category background is nice. Not sure I'm a huge fan of the `#332222` background. It'd be nice if `#040204` and/or `#7d623c` could be used, as these are the black+gold colours used in the main game UI.

**Comment by Kramin42** [comment]
Screen Shot 2020-06-12 at 11 48 47 PM

**Comment by Kramin42** [comment]
I've also tested it locally now.

**Comment by ebering** [comment]
Thanks for this!

I went with magenta for win highlighting for the Zotfeel (Very Important!)

**Pull request closed without merging**
